const ERROR_CODES = {
  VALIDATION: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  DATABASE: "DATABASE_ERROR",
  VERIFICATION: "VERIFICATION_ERROR",
  INTERNAL: "INTERNAL_ERROR"
};

export { ERROR_CODES };
